### ISSUE TITLE
[Lua - VE - Bug] VEs are not server synced

### ISSUE THREAD

**Issue by IllustrisJack** [Powback/VEManager#36]
After https://github.com/BF3RM/VEManager/pull/35 VEs are not synced anymore

**Comment by IllustrisJack** [comment]
Pls take a look @FlashHit because i sadly don´t have the time to do so

**Comment by GreatApo** [comment]
No obvious reason why...

**Comment by IllustrisJack** [comment]
@GreatApo ohh hello ;)
i fixed it with https://github.com/BF3RM/RealityMod/pull/1261

**Comment by IllustrisJack** [comment]
@BF3RM/quality-assurance 

Test if VEs are synced properly on join.
- Some1 join first (change ve to whatever)
- then some1 else joins (check if the ve is synced)

**Comment by Dumpy250** [comment]
Works as intended.
