### ISSUE TITLE
Client crash on map change

### ISSUE THREAD

**Issue by OsQw3rty** [Powback/VEManager#38]
Hi,

I've just deployed a new server in VU with the mod but every time a map is changed via normal round ending. 
Not sure if this mod is active anymore but decided to try to reach you.

I'm using the latest release of the mod with VU client and server version 19006. Also tried with "-updateBranch dev" as command option which updates to 19042 but it faced the same problem.

Is this something that is with vu version or am I configuring something wrong here.

**Comment by IllustrisJack** [comment]
Hello, are you using the latest release 0.3.4? If yes, with what mod are pairing VEManager with (as VEM doesn´t do much without another mod controlling it)?

**Comment by OsQw3rty** [comment]
I'm pairing VEManager with the BetterBF3VisualMod.
And yes, I'm using the latest version.

**Comment by IllustrisJack** [comment]
Ah ok, pls try the already bundled version from the forums https://community.veniceunleashed.net/uploads/short-url/akjhvEe6GdbsBAavm3xkwUo2TTT.zip (it´s using VEManager 0.2.7)

VEManager has had some updates till then and it may be incompatible by now.

**Comment by OsQw3rty** [comment]
Tested that out but the result was the same. It kills the client on just when starts loading next map.

**Comment by IllustrisJack** [comment]
Are you using fun bots or any other mod? Because current VEManager version runs on Reality Mod without issues.

**Comment by OsQw3rty** [comment]
Tested with only vemanager and bettervisuals mod.

**Comment by OsQw3rty** [comment]
It doesn't even throw any error, but vu closes completely, server says the players just left.

**Comment by IllustrisJack** [comment]
Could you contact me on Discord? IllustrisJack#5355
I believe this issue lies in the BetterVisuals mod not in VEManager or is a local to you issue

**Comment by OsQw3rty** [comment]
Hi, sent you a friend request. Just noticed that VU-client updated to version 19072, tested again with the never version of visuals-mod with ve-manager but still facing the same issue. And it's not just me, it kill the vu-client from all the players in the server.
